### PR TITLE
deprecate the use of inline

### PR DESCRIPTION
**Pull request by randy3k**
1. `inline::cfunction` would take a considerate amount of time to execute. The setup cycle is speeded up by compiling the interface functions at build time. The same mechanism is also used by `reticulate` to embed python.

2. As we move the compilations to build time, If JuliaCall is installed from a binary source, a compile tool (e.g., gcc) is not required to execute JuliaCall.

3. Support only Julia >0.6.

### CODE REVIEW

**Comment by randy3k** [comment]
Thanks for the invitation. It works fine locally on my mac, not sure why it fails on CIs.

**Comment by Non-Contradiction** [comment]
Looks good to me. I guess julia 0.5 support is not important at now, as more and more julia packages requires julia 0.6.

Some of the tests are broken because of update in other dependencies. I have identified them and will remove them temporarily in the tests. I will also remove test for julia 0.5.

**Comment by randy3k** [comment]
The failures seem to be related to this PR. There are errors in opening the julia library on CIs.

**Comment by Non-Contradiction** [comment]
Maybe we could still use C and dyn.load instead of Rcpp?

**Comment by randy3k** [comment]
I wanted to use c++ because it supports namespace so we don't have to worry that name collision between julia and r functions. Another more direct reason was that I was referencing `reticulate` and it uses Rcpp. 🤓

**Comment by randy3k** [comment]
Btw, feel free to switch to C and `dyn.load` at your will.

**Comment by randy3k** [comment]
It also runs on Ubuntu locally.

**Comment by Non-Contradiction** [comment]
Yes, the error seems that JuliaCall links against the wrong lib, previously after update the system libstdc++, JuliaCall should be fine to link to it. Maybe setting flags could help? How about writing a Makevars? If we use Makevar, JuliaCall needs to be shipped with julia header and we also need to determine (?) all the flags before knowing where the julia is...

The reason of #19 is that dyn.load julia lib cannot happen after the loading of testthat, (on Ubuntu, dyn.load julia lib seems to be necessary even though the compiler flags have been set, on windows and mac setting compiler flags seems to be enough, so no need to do dyn.load julia lib), there might be some conflict (?) in their dependencies. But currently we load julia lib before testthat, which is okay previously.

**Comment by randy3k** [comment]
I guess in general Julia shipped libstdc++ would conflict with Rcpp packages because they are linking to different c++ library. There are a few solutions

1. Build julia from source
2. Setting `R_LD_LIBRARY_PATH` to julia shipped library directory (not sure how well it will play)
3. `patchelf` julia shared library to use system library (again, don’t know if it works)

I really want to reproduce it locally, but it seems it only happens for some versions of `gcc/g++`

**Comment by randy3k** [comment]
Great, the `R_LD_LIBRARY_PATH` solution is working.

**Comment by randy3k** [comment]
I suspect the issue of libstdc++ would also affect the current release version of JuliaCall if a user load any Rcpp library first. We might need to add a paragraph or so in the docs to address this issue. There are at least two solutions, 1. Build Julia from source, 2. Set `R_LD_LIBRARY_PATH`

**Comment by Non-Contradiction** [comment]
We could look at <https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb> to see what language R does on travis.

Or maybe we could set the language to R and install julia instead of setting language to julia and installing R. The reason of my original use of language julia is that language R on linux doesn't ship with libR, which seems to change.

**Comment by randy3k** [comment]
I agree we should set the language to R. Let me work on it.

**Comment by randy3k** [comment]
The new travis setup is running, but the test yields
```
ERROR: ArgumentError: Module A not found in current path.

Run `Pkg.add("A")` to install the A package.
```
@Non-Contradiction Do you have any idea of why?

**Comment by randy3k** [comment]
Now it passes Linux and macOS ci tests on travis-ci and runs locally on Windows except the following error messages.

```
> library(JuliaCall)
> julia_setup()
Julia at location C:\Users\IEUser\AppData\Local\JULIA-~1.1\bin will be used.
Julia version 0.6.1 found.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall...
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
jl_uv_writecb() ERROR: broken pipe EPIPE
Finish loading setup script for JuliaCall.
> julia_eval("JULIA_HOME")
[1] "C:\\Users\\IEUser\\AppData\\Local\\JULIA-~1.1\\bin"
``` 

The remaining tasks are to fix this error message and the appveyor build.

**Comment by Non-Contradiction** [comment]
Thank you very much for all the work! I will try to look into the issues. I think I could use appveyor RDP to look into them.

**Comment by Non-Contradiction** [comment]
Previously, the c function is compiled linking to the /lib/julia libs, and there is no need to set `R_LD_LIBRARY_PATH`  on travis linux, and appveyor windows also works.  I don't find anything about linking to `lib/julia` in this PR, maybe I miss it? 

I think this may be the reason that we need to set `R_LD_LIBRARY_PATH` on travis linux and the appveyor windows doesn't work. I try to set `PATH` variable on appveyor windows but that doesn't work.... Maybe the julia libs still cannot be found unless linking to?

**Comment by randy3k** [comment]
There is no need to link against libjulia in the build time (It is the whole point of this PR). The symbols are loaded to the shared library in runtime. Therefore it allows CRAN to prepare binaries and distribute to end users.
 
Coming back to the linking issue. The reason of the need of R_LD_LIBRARY_PATH is that Julia ships with a slight different version of libstdc++ and it is not quiet compatible with the system libstdc++ (at least on Travis). If we do not set the LD path, loading any package which uses c++ (eg testthat) will result in loading the system libstdc++ and any further import of JuliaCall will fail. This is an issue independent to this PR, it was looking fine with current master just because you happened to import JuliaCall first.

**Comment by Non-Contradiction** [comment]
Dear @randy3k Do you think the `dyn.load` thing is okay? If this is good, we could merge the pull request. Thank you for the hard work!!

BTW, the warning seems to be caused by older version of `devtools` or `roxygen2`. Using newer version, the content of namespace will change and there will be no warning, and then we could still treat warnings as errors, which means the same thing to CRAN.

**Comment by randy3k** [comment]
I think that it should be better solved by using PATH variable. Does it work by adding the path to `libopenllbm` to PATH before launching R?

**Comment by Non-Contradiction** [comment]
I have tried but it doesn't solve the problem. Maybe it is because julia `libopenlibm` in windows binary is `.dll.a` file instead of `.dll`?

**Comment by Non-Contradiction** [comment]
Merged. Thank you very much. Though I still don't find an appropriate way to deal with the windows lib problem.....The dyn.load could be used temporarily.

**Comment by randy3k** [comment]
I agree. Ultimately, we may need to make sure R uses Julia c++ library instead of MSVC.

**Comment by randy3k** [comment]
Now I beleive that `dyn.load`ing `libopenlibm` is actually a correct thing to do. It is because `julia.exe` links `libjulia` and `libopenlibm` statically. To mimick the same behaviour, we'll need to either perpare our own shared object which includes both `libjulia` and `libopenlibm`. Or we'll need to load the global symbols from `libopenlibm` so that `libjulia` can make use of them.

**Pull request merged**
