### PR TITLE
Mention install_julia for downloading Julia

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by Non-Contradiction** [comment]
Thank you very much!
The md file is actually generated from the Rmd file with the same name. So the changes need to be made with the Rmd file and use RMarkdown to knit it into the md file. This could be done in RStudio easily.
Would you make the change? If not convenient for you, I'm more than willing to help.

**Comment by ChrisRackauckas** [comment]
I won't be able to do that on this computer.

**Comment by Non-Contradiction** [comment]
Thanks!

**Comment by ChrisRackauckas** [comment]
Thank you! When do you plan to tag?

**Comment by Non-Contradiction** [comment]
I am doing some little refinement now and going to submit to CRAN next week.

**Pull request merged**
