### PR TITLE
improve setup script

### PR DESCRIPTION
**Pull request by randy3k**
cf #40 

My setup time is improved from 12s to 7s.

### CODE REVIEW

**Comment by Non-Contradiction** [comment]
I think the build failure is related to the julia issue #14577: <https://github.com/JuliaLang/julia/issues/14577>
that non-precompiled package cannot be used from embedding interface, which was one of the reason to include `using RCall` in the setup script.
If there is a way to check whether a package is precompiled or not, we could certainly use it here.

**Comment by randy3k** [comment]
Even the packages have been precompiled, the caches may have been outdated. It is tricky....

There are some [internal functions](https://github.com/JuliaLang/julia/blob/7eb5d44a0caee9e7e13a956312c7ab10fbf09061/base/loading.jl#L638) which we could use, but of course, we do not want to depend too much on unexpected functions.

**Comment by Non-Contradiction** [comment]
The PR with the trick passes the tests, and it also seems to get around the problem caused by julia 14577 satisfiably.

**Comment by randy3k** [comment]
I actually don’t understand why it works. Anyway, thank you for fixing it.

**Comment by Non-Contradiction** [comment]
Merged. Thanks!

**Pull request merged**
