### PR TITLE
[WIP] Automatic wrapping of julia packages

### LINKED ISSUE #4: Cannot exit julia_console in Jupyter R Notebook
When I test JuliaCall in Jupyter R Notebook. I find that the basic functionality of JuliaCall is ok, the display is working and so are packages like Gadfly and Plots. 

And one interesting fact is that `julia_console` also works in Jupyter R Notebook, and the whole console will be in one Jupyter cell including all the commands and plots. But I cannot quit from `julia_console` and things like `exit` `quit` have no effect at all.

### PR DESCRIPTION
**Pull request by Non-Contradiction**
Implement the automatic wrapping functionality for julia functions and packages. Hope it is helpful for package developers using JuliaCall.

## Related Issue

Related to <https://github.com/JuliaDiffEq/diffeqr/issues/16>

## Example

The new code implements `JuliaCall:::julia_function` and `JuliaCall:::julia_pkg_import`, both unexported currently, which wrap functions and packages automatically. The usage is as follows:

```
JuliaCall::julia_library("DifferentialEquations")
JuliaCall::autowrap("DiffEqBase.AbstractODESolution", fields = c("t","u"))
f <- function(u,p,t) -u
u0 = 0.5
tspan = JuliaCall::julia_eval("(0., 1.)")
de <- JuliaCall:::julia_pkg_import("DifferentialEquations", c("ODEProblem", "solve"))
prob = de$ODEProblem(f, u0, tspan)
sol = de$solve(prob)
```

In progress.

### CODE REVIEW

**Comment by Non-Contradiction** [comment]
Push more commits into the branch with a more refined API.
Now the example should look like this:
```
## The above should be safe to go into the function level code.

de <- JuliaCall:::julia_pkg_import("DifferentialEquations",
                                   c("ODEProblem", "solve"))
JuliaCall:::julia_pkg_hook(de,
                           function(){
                               JuliaCall::autowrap("DiffEqBase.AbstractODESolution",
                                                   fields = c("t","u"))
                           })
time_range <- function(a, b) JuliaCall::julia_call("tuple",
                                                   a, b)

## the user code follows

f <- function(u,p,t) -u
u0 = 0.5
tspan = time_range(0, 1)
prob = de$ODEProblem(f, u0, tspan)
sol = de$solve(prob)
```

**Comment by ChrisRackauckas** [comment]
Out of curiousity, does it the call on `sol` work for the continuous output, i.e. `sol(0.4)` there?

**Comment by Non-Contradiction** [comment]
R does not support the callable object syntax. sol is not recognized as a function in R so R will not think sol() is valid.I am not sure whether I can modify the internal of JuliaCall to make sol a function so the syntax is possible. Once the syntax works, the functionality should follows.Or is there any suggestion for a new syntax, to mimic callable syntax in R?------------------ Original ------------------From: Christopher Rackauckas  <notifications@github.com>Date: Mon,Sep 23,2019 6:15 AMTo: Non-Contradiction/JuliaCall <JuliaCall@noreply.github.com>Cc: Changcheng Li <lch34677@gmail.com>, Author <author@noreply.github.com>Subject: Re: [Non-Contradiction/JuliaCall] [WIP] Automatic wrapping of juliapackages (#118)Out of curiousity, does it the call on sol work for the continuous output, i.e. sol(0.4) there?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Non-Contradiction/JuliaCall/pull/118?email_source=notifications\u0026email_token=ACPJRMW4R3SDC6C7I5S3RVLQLCJLTA5CNFSM4IZFFHJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7KMUZI#issuecomment-534039141",
"url": "https://github.com/Non-Contradiction/JuliaCall/pull/118?email_source=notifications\u0026email_token=ACPJRMW4R3SDC6C7I5S3RVLQLCJLTA5CNFSM4IZFFHJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7KMUZI#issuecomment-534039141",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ChrisRackauckas** [comment]
Maybe it can be something like `sol$.(0.4)`? I'm fine with any reasonable syntax on this: that's fixable just by documenting it.

**Comment by Non-Contradiction** [comment]
With the new commits, `sol$.(0.4)` will give the result as `sol(0.4)` in julia. 
In the commits, $juliaobject$.()` is the syntax to mimic callable objects in Julia, and one cavity is that it doesn't support keyword arguments currently.

**Comment by Non-Contradiction** [comment]
I will first merge this PR and get a new release with all the new functionalities and bug fixes. More work will be done in future PRs.

**Pull request merged**
