### PR TITLE
[WIP] Improve JuliaCall in RMarkdown and Julia Engine

### PR DESCRIPTION
**Pull request by Non-Contradiction**
The initial implementation of JuliaCall in RMarkdown is working but problematic.
For example, it only supportted html documents.

This PR should allow JuliaCall and the corresponding engine to work in all types of documents.

### CODE REVIEW

**Comment by Non-Contradiction** [comment]
Example of JuliaCall in RMarkdown in this branch can be seen at:
Rmd file: <https://github.com/Non-Contradiction/JuliaCall/blob/RMarkdown/example/JuliaCall_in_RMarkdown.Rmd>
Html result: <https://htmlpreview.github.io/?https://github.com/Non-Contradiction/JuliaCall/blob/RMarkdown/example/JuliaCall_in_RMarkdown.html>

**Comment by Non-Contradiction** [comment]
The main file of this PR is:
<https://github.com/Non-Contradiction/JuliaCall/blob/RMarkdown/R/RMarkdown.R>

**Comment by Non-Contradiction** [comment]
@yihui 

Dear Yihui,

I have talked to you about this Julia engine in the google group of knitr. 
And I have just done some improvement to the previous work.
You could see an R Markdown document example using the engine in one of the comments above.

Would you mind taking a look at and commenting the code in <https://github.com/Non-Contradiction/JuliaCall/blob/RMarkdown/R/RMarkdown.R> at your spare time?

Thank you very much.

**Comment by yihui** [comment]
I don't know much about Julia, so I cannot really provide any useful comments. The example looks awesome to me! Thanks!

**Pull request merged**
